import Head from "next/head";
import Layout from "../components/layout";
import Hero from "../components/Hero";
import css from '/styles/Home.module.css'
export default function Home() {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>Kahani Khane Ki</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Fav.png" />
        </Head>
        <main>
         <Hero/>    
        </main>
      </div>
    </Layout>
  );
}

